# Enable C++ support
language: cpp

addons:
  apt:
    sources:
      # cmake
      - george-edison55-precise-backports
      - ubuntu-toolchain-r-test  
      # c++17
      - llvm-toolchain-trusty-5.0        
    packages:
      # cmake
      - cmake-data
      - cmake
      # c++17
      - g++-7
       - clang-5.0        

# Compiler selection
compiler:
  - clang  
  - gcc

install: 
  # LHC
  - mkdir build
  - cd build
  - cmake -DLHC_TEST=True ..
  - make

# Build steps
script:
  - ./lhc_tests
 
