# Enable C++ support
language: cpp

# Update cmake
addons:
  apt:
    sources:
      - george-edison55-precise-backports
    packages:
      - cmake-data
      - cmake

# Compiler selection
compiler:
  - clang  
  - gcc

# Build steps
script:
  - mkdir build
  - cd build
  - cmake -DLHC_TEST=True ..
  - make
  - ./lhc_tests
 
